---

extends:
- airbnb
- "plugin:jest/recommended"
- "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  max-len: ["error", { code: 150 }]
  react/destructuring-assignment: 0
  react/jsx-one-expression-per-line: 0
  no-console: 0